package software.amazon.jsii.tests.calculator;

import static java.util.Arrays.asList;

import java.util.List;
import software.amazon.jsii.JsiiModule;

public final class $Module extends JsiiModule {
    public $Module() {
        super("jsii-calc", "1.0.0", $Module.class, "jsii-calc@1.0.0.jsii.tgz");
    }

    @Override
    public List<Class<? extends JsiiModule>> getDependencies() {
        return asList(software.amazon.jsii.tests.calculator.base.$Module.class, software.amazon.jsii.tests.calculator.baseofbase.$Module.class, software.amazon.jsii.tests.calculator.lib.$Module.class);
    }

    @Override
    protected Class<?> resolveClass(final String fqn) throws ClassNotFoundException {
        switch (fqn) {
            case "jsii-calc.AbstractSuite": return software.amazon.jsii.tests.calculator.AbstractSuite.class;
            case "jsii-calc.Add": return software.amazon.jsii.tests.calculator.Add.class;
            case "jsii-calc.BinaryOperation": return software.amazon.jsii.tests.calculator.BinaryOperation.class;
            case "jsii-calc.Calculator": return software.amazon.jsii.tests.calculator.Calculator.class;
            case "jsii-calc.CalculatorProps": return software.amazon.jsii.tests.calculator.CalculatorProps.class;
            case "jsii-calc.IFriendlier": return software.amazon.jsii.tests.calculator.IFriendlier.class;
            case "jsii-calc.IFriendlyRandomGenerator": return software.amazon.jsii.tests.calculator.IFriendlyRandomGenerator.class;
            case "jsii-calc.IRandomNumberGenerator": return software.amazon.jsii.tests.calculator.IRandomNumberGenerator.class;
            case "jsii-calc.MethodNamedProperty": return software.amazon.jsii.tests.calculator.MethodNamedProperty.class;
            case "jsii-calc.Multiply": return software.amazon.jsii.tests.calculator.Multiply.class;
            case "jsii-calc.Negate": return software.amazon.jsii.tests.calculator.Negate.class;
            case "jsii-calc.Power": return software.amazon.jsii.tests.calculator.Power.class;
            case "jsii-calc.PropertyNamedProperty": return software.amazon.jsii.tests.calculator.PropertyNamedProperty.class;
            case "jsii-calc.SmellyStruct": return software.amazon.jsii.tests.calculator.SmellyStruct.class;
            case "jsii-calc.Sum": return software.amazon.jsii.tests.calculator.Sum.class;
            case "jsii-calc.UnaryOperation": return software.amazon.jsii.tests.calculator.UnaryOperation.class;
            case "jsii-calc.compliance.AbstractClass": return software.amazon.jsii.tests.calculator.compliance.AbstractClass.class;
            case "jsii-calc.compliance.AbstractClassBase": return software.amazon.jsii.tests.calculator.compliance.AbstractClassBase.class;
            case "jsii-calc.compliance.AbstractClassReturner": return software.amazon.jsii.tests.calculator.compliance.AbstractClassReturner.class;
            case "jsii-calc.compliance.AllTypes": return software.amazon.jsii.tests.calculator.compliance.AllTypes.class;
            case "jsii-calc.compliance.AllTypesEnum": return software.amazon.jsii.tests.calculator.compliance.AllTypesEnum.class;
            case "jsii-calc.compliance.AllowedMethodNames": return software.amazon.jsii.tests.calculator.compliance.AllowedMethodNames.class;
            case "jsii-calc.compliance.AmbiguousParameters": return software.amazon.jsii.tests.calculator.compliance.AmbiguousParameters.class;
            case "jsii-calc.compliance.AnonymousImplementationProvider": return software.amazon.jsii.tests.calculator.compliance.AnonymousImplementationProvider.class;
            case "jsii-calc.compliance.AsyncVirtualMethods": return software.amazon.jsii.tests.calculator.compliance.AsyncVirtualMethods.class;
            case "jsii-calc.compliance.AugmentableClass": return software.amazon.jsii.tests.calculator.compliance.AugmentableClass.class;
            case "jsii-calc.compliance.BaseJsii976": return software.amazon.jsii.tests.calculator.compliance.BaseJsii976.class;
            case "jsii-calc.compliance.Bell": return software.amazon.jsii.tests.calculator.compliance.Bell.class;
            case "jsii-calc.compliance.ChildStruct982": return software.amazon.jsii.tests.calculator.compliance.ChildStruct982.class;
            case "jsii-calc.compliance.ClassThatImplementsTheInternalInterface": return software.amazon.jsii.tests.calculator.compliance.ClassThatImplementsTheInternalInterface.class;
            case "jsii-calc.compliance.ClassThatImplementsThePrivateInterface": return software.amazon.jsii.tests.calculator.compliance.ClassThatImplementsThePrivateInterface.class;
            case "jsii-calc.compliance.ClassWithCollections": return software.amazon.jsii.tests.calculator.compliance.ClassWithCollections.class;
            case "jsii-calc.compliance.ClassWithDocs": return software.amazon.jsii.tests.calculator.compliance.ClassWithDocs.class;
            case "jsii-calc.compliance.ClassWithJavaReservedWords": return software.amazon.jsii.tests.calculator.compliance.ClassWithJavaReservedWords.class;
            case "jsii-calc.compliance.ClassWithMutableObjectLiteralProperty": return software.amazon.jsii.tests.calculator.compliance.ClassWithMutableObjectLiteralProperty.class;
            case "jsii-calc.compliance.ClassWithPrivateConstructorAndAutomaticProperties": return software.amazon.jsii.tests.calculator.compliance.ClassWithPrivateConstructorAndAutomaticProperties.class;
            case "jsii-calc.compliance.ConfusingToJackson": return software.amazon.jsii.tests.calculator.compliance.ConfusingToJackson.class;
            case "jsii-calc.compliance.ConfusingToJacksonStruct": return software.amazon.jsii.tests.calculator.compliance.ConfusingToJacksonStruct.class;
            case "jsii-calc.compliance.ConstructorPassesThisOut": return software.amazon.jsii.tests.calculator.compliance.ConstructorPassesThisOut.class;
            case "jsii-calc.compliance.Constructors": return software.amazon.jsii.tests.calculator.compliance.Constructors.class;
            case "jsii-calc.compliance.ConsumePureInterface": return software.amazon.jsii.tests.calculator.compliance.ConsumePureInterface.class;
            case "jsii-calc.compliance.ConsumerCanRingBell": return software.amazon.jsii.tests.calculator.compliance.ConsumerCanRingBell.class;
            case "jsii-calc.compliance.ConsumersOfThisCrazyTypeSystem": return software.amazon.jsii.tests.calculator.compliance.ConsumersOfThisCrazyTypeSystem.class;
            case "jsii-calc.compliance.DataRenderer": return software.amazon.jsii.tests.calculator.compliance.DataRenderer.class;
            case "jsii-calc.compliance.DefaultedConstructorArgument": return software.amazon.jsii.tests.calculator.compliance.DefaultedConstructorArgument.class;
            case "jsii-calc.compliance.Demonstrate982": return software.amazon.jsii.tests.calculator.compliance.Demonstrate982.class;
            case "jsii-calc.compliance.DerivedClassHasNoProperties.Base": return software.amazon.jsii.tests.calculator.compliance.derived_class_has_no_properties.Base.class;
            case "jsii-calc.compliance.DerivedClassHasNoProperties.Derived": return software.amazon.jsii.tests.calculator.compliance.derived_class_has_no_properties.Derived.class;
            case "jsii-calc.compliance.DerivedStruct": return software.amazon.jsii.tests.calculator.compliance.DerivedStruct.class;
            case "jsii-calc.compliance.DiamondInheritanceBaseLevelStruct": return software.amazon.jsii.tests.calculator.compliance.DiamondInheritanceBaseLevelStruct.class;
            case "jsii-calc.compliance.DiamondInheritanceFirstMidLevelStruct": return software.amazon.jsii.tests.calculator.compliance.DiamondInheritanceFirstMidLevelStruct.class;
            case "jsii-calc.compliance.DiamondInheritanceSecondMidLevelStruct": return software.amazon.jsii.tests.calculator.compliance.DiamondInheritanceSecondMidLevelStruct.class;
            case "jsii-calc.compliance.DiamondInheritanceTopLevelStruct": return software.amazon.jsii.tests.calculator.compliance.DiamondInheritanceTopLevelStruct.class;
            case "jsii-calc.compliance.DisappointingCollectionSource": return software.amazon.jsii.tests.calculator.compliance.DisappointingCollectionSource.class;
            case "jsii-calc.compliance.DoNotOverridePrivates": return software.amazon.jsii.tests.calculator.compliance.DoNotOverridePrivates.class;
            case "jsii-calc.compliance.DoNotRecognizeAnyAsOptional": return software.amazon.jsii.tests.calculator.compliance.DoNotRecognizeAnyAsOptional.class;
            case "jsii-calc.compliance.DontComplainAboutVariadicAfterOptional": return software.amazon.jsii.tests.calculator.compliance.DontComplainAboutVariadicAfterOptional.class;
            case "jsii-calc.compliance.DoubleTrouble": return software.amazon.jsii.tests.calculator.compliance.DoubleTrouble.class;
            case "jsii-calc.compliance.EnumDispenser": return software.amazon.jsii.tests.calculator.compliance.EnumDispenser.class;
            case "jsii-calc.compliance.EraseUndefinedHashValues": return software.amazon.jsii.tests.calculator.compliance.EraseUndefinedHashValues.class;
            case "jsii-calc.compliance.EraseUndefinedHashValuesOptions": return software.amazon.jsii.tests.calculator.compliance.EraseUndefinedHashValuesOptions.class;
            case "jsii-calc.compliance.ExportedBaseClass": return software.amazon.jsii.tests.calculator.compliance.ExportedBaseClass.class;
            case "jsii-calc.compliance.ExtendsInternalInterface": return software.amazon.jsii.tests.calculator.compliance.ExtendsInternalInterface.class;
            case "jsii-calc.compliance.GiveMeStructs": return software.amazon.jsii.tests.calculator.compliance.GiveMeStructs.class;
            case "jsii-calc.compliance.GreetingAugmenter": return software.amazon.jsii.tests.calculator.compliance.GreetingAugmenter.class;
            case "jsii-calc.compliance.IAnonymousImplementationProvider": return software.amazon.jsii.tests.calculator.compliance.IAnonymousImplementationProvider.class;
            case "jsii-calc.compliance.IAnonymouslyImplementMe": return software.amazon.jsii.tests.calculator.compliance.IAnonymouslyImplementMe.class;
            case "jsii-calc.compliance.IAnotherPublicInterface": return software.amazon.jsii.tests.calculator.compliance.IAnotherPublicInterface.class;
            case "jsii-calc.compliance.IBell": return software.amazon.jsii.tests.calculator.compliance.IBell.class;
            case "jsii-calc.compliance.IBellRinger": return software.amazon.jsii.tests.calculator.compliance.IBellRinger.class;
            case "jsii-calc.compliance.IConcreteBellRinger": return software.amazon.jsii.tests.calculator.compliance.IConcreteBellRinger.class;
            case "jsii-calc.compliance.IExtendsPrivateInterface": return software.amazon.jsii.tests.calculator.compliance.IExtendsPrivateInterface.class;
            case "jsii-calc.compliance.IInterfaceImplementedByAbstractClass": return software.amazon.jsii.tests.calculator.compliance.IInterfaceImplementedByAbstractClass.class;
            case "jsii-calc.compliance.IInterfaceThatShouldNotBeADataType": return software.amazon.jsii.tests.calculator.compliance.IInterfaceThatShouldNotBeADataType.class;
            case "jsii-calc.compliance.IInterfaceWithInternal": return software.amazon.jsii.tests.calculator.compliance.IInterfaceWithInternal.class;
            case "jsii-calc.compliance.IInterfaceWithMethods": return software.amazon.jsii.tests.calculator.compliance.IInterfaceWithMethods.class;
            case "jsii-calc.compliance.IInterfaceWithOptionalMethodArguments": return software.amazon.jsii.tests.calculator.compliance.IInterfaceWithOptionalMethodArguments.class;
            case "jsii-calc.compliance.IInterfaceWithProperties": return software.amazon.jsii.tests.calculator.compliance.IInterfaceWithProperties.class;
            case "jsii-calc.compliance.IInterfaceWithPropertiesExtension": return software.amazon.jsii.tests.calculator.compliance.IInterfaceWithPropertiesExtension.class;
            case "jsii-calc.compliance.IMutableObjectLiteral": return software.amazon.jsii.tests.calculator.compliance.IMutableObjectLiteral.class;
            case "jsii-calc.compliance.INonInternalInterface": return software.amazon.jsii.tests.calculator.compliance.INonInternalInterface.class;
            case "jsii-calc.compliance.IObjectWithProperty": return software.amazon.jsii.tests.calculator.compliance.IObjectWithProperty.class;
            case "jsii-calc.compliance.IOptionalMethod": return software.amazon.jsii.tests.calculator.compliance.IOptionalMethod.class;
            case "jsii-calc.compliance.IPrivatelyImplemented": return software.amazon.jsii.tests.calculator.compliance.IPrivatelyImplemented.class;
            case "jsii-calc.compliance.IPublicInterface": return software.amazon.jsii.tests.calculator.compliance.IPublicInterface.class;
            case "jsii-calc.compliance.IPublicInterface2": return software.amazon.jsii.tests.calculator.compliance.IPublicInterface2.class;
            case "jsii-calc.compliance.IReturnJsii976": return software.amazon.jsii.tests.calculator.compliance.IReturnJsii976.class;
            case "jsii-calc.compliance.IReturnsNumber": return software.amazon.jsii.tests.calculator.compliance.IReturnsNumber.class;
            case "jsii-calc.compliance.IStructReturningDelegate": return software.amazon.jsii.tests.calculator.compliance.IStructReturningDelegate.class;
            case "jsii-calc.compliance.ImplementInternalInterface": return software.amazon.jsii.tests.calculator.compliance.ImplementInternalInterface.class;
            case "jsii-calc.compliance.Implementation": return software.amazon.jsii.tests.calculator.compliance.Implementation.class;
            case "jsii-calc.compliance.ImplementsInterfaceWithInternal": return software.amazon.jsii.tests.calculator.compliance.ImplementsInterfaceWithInternal.class;
            case "jsii-calc.compliance.ImplementsInterfaceWithInternalSubclass": return software.amazon.jsii.tests.calculator.compliance.ImplementsInterfaceWithInternalSubclass.class;
            case "jsii-calc.compliance.ImplementsPrivateInterface": return software.amazon.jsii.tests.calculator.compliance.ImplementsPrivateInterface.class;
            case "jsii-calc.compliance.ImplictBaseOfBase": return software.amazon.jsii.tests.calculator.compliance.ImplictBaseOfBase.class;
            case "jsii-calc.compliance.InbetweenClass": return software.amazon.jsii.tests.calculator.compliance.InbetweenClass.class;
            case "jsii-calc.compliance.InterfaceCollections": return software.amazon.jsii.tests.calculator.compliance.InterfaceCollections.class;
            case "jsii-calc.compliance.InterfaceInNamespaceIncludesClasses.Foo": return software.amazon.jsii.tests.calculator.compliance.interface_in_namespace_includes_classes.Foo.class;
            case "jsii-calc.compliance.InterfaceInNamespaceIncludesClasses.Hello": return software.amazon.jsii.tests.calculator.compliance.interface_in_namespace_includes_classes.Hello.class;
            case "jsii-calc.compliance.InterfaceInNamespaceOnlyInterface.Hello": return software.amazon.jsii.tests.calculator.compliance.interface_in_namespace_only_interface.Hello.class;
            case "jsii-calc.compliance.InterfacesMaker": return software.amazon.jsii.tests.calculator.compliance.InterfacesMaker.class;
            case "jsii-calc.compliance.JSObjectLiteralForInterface": return software.amazon.jsii.tests.calculator.compliance.JSObjectLiteralForInterface.class;
            case "jsii-calc.compliance.JSObjectLiteralToNative": return software.amazon.jsii.tests.calculator.compliance.JSObjectLiteralToNative.class;
            case "jsii-calc.compliance.JSObjectLiteralToNativeClass": return software.amazon.jsii.tests.calculator.compliance.JSObjectLiteralToNativeClass.class;
            case "jsii-calc.compliance.JavaReservedWords": return software.amazon.jsii.tests.calculator.compliance.JavaReservedWords.class;
            case "jsii-calc.compliance.JsiiAgent": return software.amazon.jsii.tests.calculator.compliance.JsiiAgent.class;
            case "jsii-calc.compliance.JsonFormatter": return software.amazon.jsii.tests.calculator.compliance.JsonFormatter.class;
            case "jsii-calc.compliance.LoadBalancedFargateServiceProps": return software.amazon.jsii.tests.calculator.compliance.LoadBalancedFargateServiceProps.class;
            case "jsii-calc.compliance.NestedStruct": return software.amazon.jsii.tests.calculator.compliance.NestedStruct.class;
            case "jsii-calc.compliance.NodeStandardLibrary": return software.amazon.jsii.tests.calculator.compliance.NodeStandardLibrary.class;
            case "jsii-calc.compliance.NullShouldBeTreatedAsUndefined": return software.amazon.jsii.tests.calculator.compliance.NullShouldBeTreatedAsUndefined.class;
            case "jsii-calc.compliance.NullShouldBeTreatedAsUndefinedData": return software.amazon.jsii.tests.calculator.compliance.NullShouldBeTreatedAsUndefinedData.class;
            case "jsii-calc.compliance.NumberGenerator": return software.amazon.jsii.tests.calculator.compliance.NumberGenerator.class;
            case "jsii-calc.compliance.ObjectRefsInCollections": return software.amazon.jsii.tests.calculator.compliance.ObjectRefsInCollections.class;
            case "jsii-calc.compliance.ObjectWithPropertyProvider": return software.amazon.jsii.tests.calculator.compliance.ObjectWithPropertyProvider.class;
            case "jsii-calc.compliance.OptionalArgumentInvoker": return software.amazon.jsii.tests.calculator.compliance.OptionalArgumentInvoker.class;
            case "jsii-calc.compliance.OptionalConstructorArgument": return software.amazon.jsii.tests.calculator.compliance.OptionalConstructorArgument.class;
            case "jsii-calc.compliance.OptionalStruct": return software.amazon.jsii.tests.calculator.compliance.OptionalStruct.class;
            case "jsii-calc.compliance.OptionalStructConsumer": return software.amazon.jsii.tests.calculator.compliance.OptionalStructConsumer.class;
            case "jsii-calc.compliance.OverridableProtectedMember": return software.amazon.jsii.tests.calculator.compliance.OverridableProtectedMember.class;
            case "jsii-calc.compliance.OverrideReturnsObject": return software.amazon.jsii.tests.calculator.compliance.OverrideReturnsObject.class;
            case "jsii-calc.compliance.ParentStruct982": return software.amazon.jsii.tests.calculator.compliance.ParentStruct982.class;
            case "jsii-calc.compliance.PartiallyInitializedThisConsumer": return software.amazon.jsii.tests.calculator.compliance.PartiallyInitializedThisConsumer.class;
            case "jsii-calc.compliance.Polymorphism": return software.amazon.jsii.tests.calculator.compliance.Polymorphism.class;
            case "jsii-calc.compliance.PublicClass": return software.amazon.jsii.tests.calculator.compliance.PublicClass.class;
            case "jsii-calc.compliance.PythonReservedWords": return software.amazon.jsii.tests.calculator.compliance.PythonReservedWords.class;
            case "jsii-calc.compliance.ReferenceEnumFromScopedPackage": return software.amazon.jsii.tests.calculator.compliance.ReferenceEnumFromScopedPackage.class;
            case "jsii-calc.compliance.ReturnsPrivateImplementationOfInterface": return software.amazon.jsii.tests.calculator.compliance.ReturnsPrivateImplementationOfInterface.class;
            case "jsii-calc.compliance.RootStruct": return software.amazon.jsii.tests.calculator.compliance.RootStruct.class;
            case "jsii-calc.compliance.RootStructValidator": return software.amazon.jsii.tests.calculator.compliance.RootStructValidator.class;
            case "jsii-calc.compliance.RuntimeTypeChecking": return software.amazon.jsii.tests.calculator.compliance.RuntimeTypeChecking.class;
            case "jsii-calc.compliance.SecondLevelStruct": return software.amazon.jsii.tests.calculator.compliance.SecondLevelStruct.class;
            case "jsii-calc.compliance.SingleInstanceTwoTypes": return software.amazon.jsii.tests.calculator.compliance.SingleInstanceTwoTypes.class;
            case "jsii-calc.compliance.SingletonInt": return software.amazon.jsii.tests.calculator.compliance.SingletonInt.class;
            case "jsii-calc.compliance.SingletonIntEnum": return software.amazon.jsii.tests.calculator.compliance.SingletonIntEnum.class;
            case "jsii-calc.compliance.SingletonString": return software.amazon.jsii.tests.calculator.compliance.SingletonString.class;
            case "jsii-calc.compliance.SingletonStringEnum": return software.amazon.jsii.tests.calculator.compliance.SingletonStringEnum.class;
            case "jsii-calc.compliance.SomeTypeJsii976": return software.amazon.jsii.tests.calculator.compliance.SomeTypeJsii976.class;
            case "jsii-calc.compliance.StaticContext": return software.amazon.jsii.tests.calculator.compliance.StaticContext.class;
            case "jsii-calc.compliance.Statics": return software.amazon.jsii.tests.calculator.compliance.Statics.class;
            case "jsii-calc.compliance.StringEnum": return software.amazon.jsii.tests.calculator.compliance.StringEnum.class;
            case "jsii-calc.compliance.StripInternal": return software.amazon.jsii.tests.calculator.compliance.StripInternal.class;
            case "jsii-calc.compliance.StructA": return software.amazon.jsii.tests.calculator.compliance.StructA.class;
            case "jsii-calc.compliance.StructB": return software.amazon.jsii.tests.calculator.compliance.StructB.class;
            case "jsii-calc.compliance.StructParameterType": return software.amazon.jsii.tests.calculator.compliance.StructParameterType.class;
            case "jsii-calc.compliance.StructPassing": return software.amazon.jsii.tests.calculator.compliance.StructPassing.class;
            case "jsii-calc.compliance.StructUnionConsumer": return software.amazon.jsii.tests.calculator.compliance.StructUnionConsumer.class;
            case "jsii-calc.compliance.StructWithJavaReservedWords": return software.amazon.jsii.tests.calculator.compliance.StructWithJavaReservedWords.class;
            case "jsii-calc.compliance.SupportsNiceJavaBuilder": return software.amazon.jsii.tests.calculator.compliance.SupportsNiceJavaBuilder.class;
            case "jsii-calc.compliance.SupportsNiceJavaBuilderProps": return software.amazon.jsii.tests.calculator.compliance.SupportsNiceJavaBuilderProps.class;
            case "jsii-calc.compliance.SupportsNiceJavaBuilderWithRequiredProps": return software.amazon.jsii.tests.calculator.compliance.SupportsNiceJavaBuilderWithRequiredProps.class;
            case "jsii-calc.compliance.SyncVirtualMethods": return software.amazon.jsii.tests.calculator.compliance.SyncVirtualMethods.class;
            case "jsii-calc.compliance.Thrower": return software.amazon.jsii.tests.calculator.compliance.Thrower.class;
            case "jsii-calc.compliance.TopLevelStruct": return software.amazon.jsii.tests.calculator.compliance.TopLevelStruct.class;
            case "jsii-calc.compliance.UnionProperties": return software.amazon.jsii.tests.calculator.compliance.UnionProperties.class;
            case "jsii-calc.compliance.UseBundledDependency": return software.amazon.jsii.tests.calculator.compliance.UseBundledDependency.class;
            case "jsii-calc.compliance.UseCalcBase": return software.amazon.jsii.tests.calculator.compliance.UseCalcBase.class;
            case "jsii-calc.compliance.UsesInterfaceWithProperties": return software.amazon.jsii.tests.calculator.compliance.UsesInterfaceWithProperties.class;
            case "jsii-calc.compliance.VariadicInvoker": return software.amazon.jsii.tests.calculator.compliance.VariadicInvoker.class;
            case "jsii-calc.compliance.VariadicMethod": return software.amazon.jsii.tests.calculator.compliance.VariadicMethod.class;
            case "jsii-calc.compliance.VirtualMethodPlayground": return software.amazon.jsii.tests.calculator.compliance.VirtualMethodPlayground.class;
            case "jsii-calc.compliance.VoidCallback": return software.amazon.jsii.tests.calculator.compliance.VoidCallback.class;
            case "jsii-calc.compliance.WithPrivatePropertyInConstructor": return software.amazon.jsii.tests.calculator.compliance.WithPrivatePropertyInConstructor.class;
            case "jsii-calc.composition.CompositeOperation": return software.amazon.jsii.tests.calculator.composition.CompositeOperation.class;
            case "jsii-calc.composition.CompositeOperation.CompositionStringStyle": return software.amazon.jsii.tests.calculator.composition.CompositeOperation.CompositionStringStyle.class;
            case "jsii-calc.documented.DocumentedClass": return software.amazon.jsii.tests.calculator.documented.DocumentedClass.class;
            case "jsii-calc.documented.Greetee": return software.amazon.jsii.tests.calculator.documented.Greetee.class;
            case "jsii-calc.documented.Old": return software.amazon.jsii.tests.calculator.documented.Old.class;
            case "jsii-calc.erasureTests.IJSII417Derived": return software.amazon.jsii.tests.calculator.erasure_tests.IJSII417Derived.class;
            case "jsii-calc.erasureTests.IJSII417PublicBaseOfBase": return software.amazon.jsii.tests.calculator.erasure_tests.IJSII417PublicBaseOfBase.class;
            case "jsii-calc.erasureTests.IJsii487External": return software.amazon.jsii.tests.calculator.erasure_tests.IJsii487External.class;
            case "jsii-calc.erasureTests.IJsii487External2": return software.amazon.jsii.tests.calculator.erasure_tests.IJsii487External2.class;
            case "jsii-calc.erasureTests.IJsii496": return software.amazon.jsii.tests.calculator.erasure_tests.IJsii496.class;
            case "jsii-calc.erasureTests.JSII417Derived": return software.amazon.jsii.tests.calculator.erasure_tests.JSII417Derived.class;
            case "jsii-calc.erasureTests.JSII417PublicBaseOfBase": return software.amazon.jsii.tests.calculator.erasure_tests.JSII417PublicBaseOfBase.class;
            case "jsii-calc.erasureTests.Jsii487Derived": return software.amazon.jsii.tests.calculator.erasure_tests.Jsii487Derived.class;
            case "jsii-calc.erasureTests.Jsii496Derived": return software.amazon.jsii.tests.calculator.erasure_tests.Jsii496Derived.class;
            case "jsii-calc.stability_annotations.DeprecatedClass": return software.amazon.jsii.tests.calculator.stability_annotations.DeprecatedClass.class;
            case "jsii-calc.stability_annotations.DeprecatedEnum": return software.amazon.jsii.tests.calculator.stability_annotations.DeprecatedEnum.class;
            case "jsii-calc.stability_annotations.DeprecatedStruct": return software.amazon.jsii.tests.calculator.stability_annotations.DeprecatedStruct.class;
            case "jsii-calc.stability_annotations.ExperimentalClass": return software.amazon.jsii.tests.calculator.stability_annotations.ExperimentalClass.class;
            case "jsii-calc.stability_annotations.ExperimentalEnum": return software.amazon.jsii.tests.calculator.stability_annotations.ExperimentalEnum.class;
            case "jsii-calc.stability_annotations.ExperimentalStruct": return software.amazon.jsii.tests.calculator.stability_annotations.ExperimentalStruct.class;
            case "jsii-calc.stability_annotations.IDeprecatedInterface": return software.amazon.jsii.tests.calculator.stability_annotations.IDeprecatedInterface.class;
            case "jsii-calc.stability_annotations.IExperimentalInterface": return software.amazon.jsii.tests.calculator.stability_annotations.IExperimentalInterface.class;
            case "jsii-calc.stability_annotations.IStableInterface": return software.amazon.jsii.tests.calculator.stability_annotations.IStableInterface.class;
            case "jsii-calc.stability_annotations.StableClass": return software.amazon.jsii.tests.calculator.stability_annotations.StableClass.class;
            case "jsii-calc.stability_annotations.StableEnum": return software.amazon.jsii.tests.calculator.stability_annotations.StableEnum.class;
            case "jsii-calc.stability_annotations.StableStruct": return software.amazon.jsii.tests.calculator.stability_annotations.StableStruct.class;
            default: throw new ClassNotFoundException("Unknown JSII type: " + fqn);
        }
    }
}
