# See https://doc.mergify.io

pull_request_rules:
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request is now being automatically merged.
      merge:
        strict: smart
        method: squash
        strict_method: merge
      delete_head_branch: {}
      dismiss_reviews: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=^(blocked|do-not-merge)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=AWS CodeBuild us-east-1 (jsii-build)
      - status-success=Semantic Pull Request
  - name: comment checklist
    actions:
      comment:
        message: |
          ### Pull Request Checklist
          * [ ] Testing
            - Unit test added (prefer not to modify an existing test, otherwise, it's probably a breaking change)
          * [ ] Title and Description
            - __Change type__: title prefixed with **fix**, **feat** and module name in parens, which will appear in changelog
            - __Title__: use lower-case and doesn't end with a period
            - __Breaking?__: last paragraph: 'BREAKING CHANGE: <describe what changed + link for details>'
            - __Issues__: Indicate issues fixed via: '**Fixes #xxx**' or '**Closes #xxx**'
    conditions:
      - base=master
  - name: remove stale reviews
    actions:
      dismiss_reviews: {}
    conditions:
      - base=master
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.
    conditions:
      - -status-success=Semantic Pull Request
