# See https://doc.mergify.io

pull_request_rules:
  - name: automatic merge
    actions:
      comment:
        message: |
          Thank you for contributing! :heart: I will now look into making sure
          the PR is up-to-date, then proceed to try and merge it!
      merge:
        strict: smart
        method: squash
        strict_method: merge
      dismiss_reviews:
        approved: true
        changes_requested: false
    conditions:
      - -title~=(WIP|wip)
      - label!=blocked
      - label!=do-not-merge
      - -merged
      - -closed
      - -approved-reviews-by~=author
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - status-success=AWS CodeBuild us-east-1 (jsii-build)
      - status-success=continuous-integration/travis-ci/pr
      - status-success=Semantic Pull Request
  - name: delete branch after merge
    actions:
      delete_head_branch: {}
    conditions:
      - merged
  - name: if fails conventional commits
    actions:
      comment:
        message: |
          The title of this Pull Request does not conform with [Conventional Commits] guidelines. It
          will need to be adjusted before the PR can be merged.

          [Conventional Commits]: https://www.conventionalcommits.org
    conditions:
      - -status-success=Semantic Pull Request
