version: 0.2

phases:
  install:
    commands:
      - npm run bootstrap
  pre_build:
    commands:
      - npm run fetch-dotnet-snk
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - '[ ${CODEBUILD_BUILD_SUCCEEDING} = 1 ] && npm run package'
artifacts:
  files:
    - "**/*"
  base-directory: dist
