version: 0.2

phases:
  install:
    commands:
      - /bin/bash ./install.sh
  pre_build:
    commands:
      - /bin/bash ./fetch-dotnet-snk.sh
  build:
    commands:
      - /bin/bash ./build.sh
  post_build:
    commands:
      - "[ -f .BUILD_COMPLETED ] && /bin/bash ./pack.sh"
      - git diff-index --exit-code --ignore-space-at-eol --stat HEAD
artifacts:
  files:
    - "**/*"
  base-directory: dist
