Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 1000

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.2
