---
title: Specification
nav:
  - 1-introduction.md
  - The jsii type system: 2-type-system.md
  - The jsii kernel API: 3-kernel-api.md
  - 4-standard-compliance-suite.md
  - 5-new-language-intake.md
  - 6-compliance-report.md
