#!/bin/bash
set -euo pipefail
outdir=src/test
jsii-pacmak --target java --outdir ${outdir} node_modules/jsii-calc-lib/dist
jsii-pacmak --target java --outdir ${outdir} node_modules/jsii-calc/dist

# generate a java constant with the version number we should expect from jsii-runtime
version="$(node -e "console.log(require('./package.json').version)")"
version_java="src/main/java/org/jsii/JsiiVersion.java"
echo "Generating ${version_java} with version ${version}"

cat > ${version_java} <<HERE
// This file is generated by generate.sh
package org.jsii;

class JsiiVersion {
    public static final String RUNTIME_VERSION = "jsii-runtime@${version}";
}
HERE
