Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 1000

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  # Ruby 2.4 - EOL 2020-03-31 - https://www.ruby-lang.org/en/downloads/branches/
  TargetRubyVersion: 2.4
