const jsiiJavaRuntime = require('@jsii/java-runtime');
const path = require('path');

process.stdout.write(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. -->
<!-- SPDX-License-Identifier: Apache-2.0 -->
<settings xmlns="http://maven.apache.org/POM/4.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <!-- Generated by ${__filename} at ${new Date().toISOString()} -->

    <localRepository>${path.resolve(__dirname, 'project', '.m2', 'repository')}</localRepository>
</settings>
`);
