---
# See: https://dependabot.com/docs/config-file/
version: 1
update_configs:
  # Dependabot will detect the lerna mono-repo and discover packages in there
  - directory: /
    package_manager: javascript
    update_schedule: live
    version_requirement_updates: increase_versions
    default_labels:
      - dependencies

  - directory: /
    package_manager: dotnet:nuget
    update_schedule: daily
    default_labels:
      - dependencies
      - language/dotnet

  - directory: /
    package_manager: python
    update_schedule: live
    version_requirement_updates: auto
    default_labels:
      - dependencies
      - language/python

  - directory: /
    package_manager: ruby:bundler
    update_schedule: live
    version_requirement_updates: increase_versions
    default_labels:
      - dependencies
      - language/ruby
