---
env:
  jest: true
  node: true

plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/unbound-method': off
