# Automatically manage PRs made by Dependabot

name: Dependabot Pull Requests
on:
  pull_request:
    branches:
      - main
    paths:
      - "!**"                         # <-- Excludes everything by default
      - "**/package.json"             # <-- Allows modfying any package.json
      - "**/*.csproj"                 # <-- Allows modifying any .csproj file
      - "**/Directory.Build.targets"  # <-- Allows modifying any Directory.Build.targets file
      - "yarn.lock"                   # <-- Allows modifying yarn.lock
    types:
      - opened

jobs:
  approve:
    name: Auto-Approve
    if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Request @dependabot auto-merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: 'squash and merge'
          github-token: ${{ secrets.AUTO_APPROVE_GITHUB_TOKEN }}
          target: minor
