# Workflows pertaining to the jsii/superchain Docker image
name: Docker Images

on:
  pull_request:
    branches: [main, master, release]
    # For PRs, only run if there are changes around the Dockerfile
    paths: ['superchain/**']
  push:
    branches: [main, master, release]

jobs:
  superchain:
    name: jsii/superchain
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build Image
        run: |-
          docker build                                                          \
            --pull                                                              \
            --build-arg BUILD_TIMESTAMP="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"      \
            --build-arg COMMIT_ID='${{ github.sha }}'                           \
            --tag 'jsii/superchain:nightly'                                     \
            ./superchain
      - name: Test Image
        run: |-
          docker run                                                            \
            --rm                                                                \
            --tty                                                               \
            --network=host                                                      \
            -v${{ github.workspace }}:${{ github.workspace }}                   \
            -w${{ github.workspace }}                                           \
            'jsii/superchain:nightly'                                           \
            bash -c "yarn install --frozen-lockfile && yarn build && yarn test"
      - name: Dump Image
        run: |-
          docker image save 'jsii/superchain:nightly'                           \
            > ${{ runner.temp }}/jsii-superchain.nightly.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'jsii-superchain.nightly'
          path: ${{ runner.temp }}/jsii-superchain.nightly.tar
