import * as fs from 'fs';
import * as path from 'path';

import * as schema from './schema';

/**
 * Where the generated suite pages are written, relative to the specification pages.
 */
export const SUITE_PAGES_DIR = 'compliance-suite';

const SPECIFICATION_DIR = path.join(
  __dirname,
  '..',
  '..',
  'gh-pages',
  'content',
  'specification',
);

const GENERATED_NOTICE =
  '<!-- Auto generated by tools/jsii-compliance/report.ts - do not modify by hand -->';

/**
 * The link to a test case, relative to the specification pages.
 */
export function testCaseLink(testCase: schema.TestCase): string {
  return `${SUITE_PAGES_DIR}/${testCase.category}.md#${anchor(testCase)}`;
}

/**
 * Writes one page per category, containing all test cases of the category.
 */
export function writeSuitePages(suite: schema.Suite) {
  const outdir = path.join(SPECIFICATION_DIR, SUITE_PAGES_DIR);
  fs.rmSync(outdir, { recursive: true, force: true });
  fs.mkdirSync(outdir, { recursive: true });

  for (const category of suite.categories) {
    const sections = category.testCases.map(renderTestCase);
    const page = [
      GENERATED_NOTICE,
      `# ${category.title}`,
      category.description,
      ...sections,
    ].join('\n\n');
    fs.writeFileSync(path.join(outdir, `${category.id}.md`), `${page}\n`);
  }

  // Navigation for mkdocs-awesome-pages-plugin
  const nav = suite.categories
    .map((c) => `  - ${JSON.stringify(c.title)}: ${c.id}.md`)
    .join('\n');
  fs.writeFileSync(
    path.join(outdir, '.pages.yml'),
    `---\ntitle: Test Suite\nnav:\n${nav}\n`,
  );

  console.log(`Suite pages written to ${outdir}`);
}

function renderTestCase(testCase: schema.TestCase): string {
  return [
    `<a id="${anchor(testCase)}"></a>`,
    '',
    `## ${testCase.title}`,
    '',
    `**Test:** \`${testCase.name}\``,
    '',
    demoteHeadings(collapseReferenceImplementation(testCase.body)),
  ].join('\n');
}

const REFERENCE_IMPLEMENTATION_HEADING = '## Reference Implementation';

/**
 * Wraps the "Reference Implementation" section in a collapsible block that is closed by default.
 *
 * Uses the `pymdownx.details` syntax (`??? note "Title"`), whose content must be indented by four spaces.
 * The section ends at the next heading of the same level (outside of code blocks) or at the end of the body.
 */
function collapseReferenceImplementation(markdown: string): string {
  const lines = markdown.split('\n');
  const result: string[] = [];

  let inCode = false;
  let collapsing = false;

  for (const line of lines) {
    const isFence = line.startsWith('```');
    const isHeading = !inCode && !isFence && /^## /.test(line);

    if (isHeading && collapsing) {
      collapsing = false;
    }

    if (isHeading && line === REFERENCE_IMPLEMENTATION_HEADING) {
      collapsing = true;
      // The blank line that follows the heading in the source provides the separation
      result.push('??? note "Reference Implementation"');
      continue;
    }

    if (collapsing) {
      result.push(line === '' ? line : `    ${line}`);
    } else {
      result.push(line);
    }

    if (isFence) {
      inCode = !inCode;
    }
  }

  return result.join('\n');
}

function anchor(testCase: schema.TestCase): string {
  return testCase.name;
}

/**
 * Shifts all headings outside of code blocks one level down, so the test case sections nest under the test title.
 */
function demoteHeadings(markdown: string): string {
  let inCode = false;
  return markdown
    .split('\n')
    .map((line) => {
      if (line.startsWith('```')) {
        inCode = !inCode;
      }
      return !inCode && /^#+ /.test(line) ? `#${line}` : line;
    })
    .join('\n');
}
